#!/usr/bin/env bash

# This script generates some custom buildroot files for my BeagleBone Black that
# are derived from files in the main buildroot source tree. There is no easy way
# to patch these files declaratively, so I copy them here and modify them.

set -eu

# Custom kernel config
kernel_config_fragment="board/reaver/beaglebone/kernel.fragment"
printf "# THIS FILE IS AUTOGENERATED! See generate-files.sh\n\n" > "$kernel_config_fragment"
cat <<'EOF' >> "$kernel_config_fragment"
CONFIG_NFS_FS=y
CONFIG_NFS_V3=y
CONFIG_NFS_V4=y
EOF

# defconfig
defconfig_file="configs/reaver_beaglebone_defconfig"
printf "# THIS FILE IS AUTOGENERATED! See generate-files.sh\n\n" > "$defconfig_file"

cat ../buildroot/configs/beaglebone_defconfig >> "$defconfig_file"

cat <<EOF >> "$defconfig_file"

# Custom stuff starts here
BR2_SYSTEM_DHCP="eth0" # Use eth0 for DHCP

BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES="\$(BR2_EXTERNAL_REAVER_BEAGLEBONE_PATH)/$kernel_config_fragment"

BR2_PACKAGE_DROPBEAR=y

BR2_ROOTFS_OVERLAY="\$(BR2_EXTERNAL_REAVER_BEAGLEBONE_PATH)/board/reaver/beaglebone/overlay/"
EOF
