#!/usr/bin/env bash

# This script generates some custom buildroot files for my raspberry pi that are
# derived from files in the main buildroot source tree. There is no easy way to
# patch these files declaratively, so I copy them here and modify them.

set -eu

# defconfig
defconfig_file="configs/reaver_rpi_defconfig"
printf "# THIS FILE IS AUTOGENERATED! See generate-files.sh\n\n" > "$defconfig_file"
cat ../buildroot/configs/raspberrypi4_64_defconfig >> "$defconfig_file"
cat <<'EOF' >> "$defconfig_file"
BR2_PACKAGE_DROPBEAR=y

BR2_ROOTFS_OVERLAY="$(BR2_EXTERNAL_REAVER_RPI_PATH)/board/reaver/rpi/overlay/"
EOF
